# Below code generated by Perplexity AI
from unittest.mock import patch, MagicMock
import power_analysis

def test_print_output():
    # Act
    with patch('builtins.print') as mock_print:
        power_analysis.main()

        # Assert
        mock_print.assert_called_once_with('Sample size needed: 668')
